<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class WearlyTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('wearly')->insert([
            [
                'product_id' => 'SP0001',
                'product_name' => 'Váy liền hoa nhí',
                'quantity' => 10,
                'price' => 420000,
                'material' => 'Voan',
                'type' => 'Váy',
                'size' => 'M',
                'note' => 'Mẫu mới hè 2025',
                'supplier_id' => 'MCC001',
                'supplier_name' => 'Thời Trang Ruby',
                'tax' => '8754921687',
                'address' => 'Đống Đa, Hà Nội',
                'phone' => '0911284009',
                'email' => 'tt.ruby@gmail.com',
                'stock_in_id' => 'MPN001',
                'import_date' => '2025-06-08',
                'staff_id' => 'NV001',
                'stock_out_id' => 'MPX001',
                'export_date' => '2025-06-10',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 'SP0002',
                'product_name' => 'Áo phông nữ basic',
                'quantity' => 20,
                'price' => 150000,
                'material' => 'Cotton',
                'type' => 'Áo',
                'size' => 'L',
                'note' => null,
                'supplier_id' => 'MCC002',
                'supplier_name' => 'May Mặc Hà Thành',
                'tax' => '3703337036',
                'address' => 'Mỹ Đình, Hà Nội',
                'phone' => '0988345610',
                'email' => 'mhathanh@gmail.com',
                'stock_in_id' => 'MPN002',
                'import_date' => '2025-06-09',
                'staff_id' => 'NV002',
                'stock_out_id' => 'MPX002',
                'export_date' => '2025-06-11',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 'SP0003',
                'product_name' => 'Đầm suông dáng dài',
                'quantity' => 8,
                'price' => 570000,
                'material' => 'Lụa',
                'type' => 'Đầm',
                'size' => 'XL',
                'note' => 'Best seller',
                'supplier_id' => 'MCC003',
                'supplier_name' => 'Mặc Tỉnh Dress',
                'tax' => '8709998635',
                'address' => 'Từ Sơn, Bắc Ninh',
                'phone' => '0398776395',
                'email' => 'tinhdrss44@gmail.com',
                'stock_in_id' => 'MPN003',
                'import_date' => '2025-06-10',
                'staff_id' => 'NV003',
                'stock_out_id' => 'MPX003',
                'export_date' => '2025-06-12',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 'SP0004',
                'product_name' => 'Chân váy bút chì công sở',
                'quantity' => 16,
                'price' => 230000,
                'material' => 'Kaki',
                'type' => 'Váy',
                'size' => 'L',
                'note' => null,
                'supplier_id' => 'MCC001',
                'supplier_name' => 'Thời Trang Ruby',
                'tax' => '8754921687',
                'address' => 'Đống Đa, Hà Nội',
                'phone' => '0911284009',
                'email' => 'tt.ruby@gmail.com',
                'stock_in_id' => 'MPN004',
                'import_date' => '2025-06-11',
                'staff_id' => 'NV004',
                'stock_out_id' => 'MPX004',
                'export_date' => '2025-06-13',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 'SP0005',
                'product_name' => 'Áo sơ mi nữ cổ V',
                'quantity' => 18,
                'price' => 270000,
                'material' => 'Voan lụa',
                'type' => 'Áo',
                'size' => 'M',
                'note' => 'Màu trắng',
                'supplier_id' => 'MCC002',
                'supplier_name' => 'May Mặc Hà Thành',
                'tax' => '3703337036',
                'address' => 'Mỹ Đình, Hà Nội',
                'phone' => '0988345610',
                'email' => 'mhathanh@gmail.com',
                'stock_in_id' => 'MPN002',
                'import_date' => '2025-06-09',
                'staff_id' => 'NV002',
                'stock_out_id' => 'MPX005',
                'export_date' => '2025-06-14',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 'SP0006',
                'product_name' => 'Áo vest nữ công sở',
                'quantity' => 7,
                'price' => 650000,
                'material' => 'Tweed',
                'type' => 'Áo',
                'size' => 'L',
                'note' => 'Set vest',
                'supplier_id' => 'MCC005',
                'supplier_name' => 'Vest Bảo An',
                'tax' => '9923894822',
                'address' => 'Nam Từ Liêm, Hà Nội',
                'phone' => '0934819201',
                'email' => 'vestbaoan@gmail.com',
                'stock_in_id' => 'MPN005',
                'import_date' => '2025-06-12',
                'staff_id' => 'NV002',
                'stock_out_id' => 'MPX006',
                'export_date' => '2025-06-15',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 'SP0007',
                'product_name' => 'Cardigan len nữ',
                'quantity' => 14,
                'price' => 310000,
                'material' => 'Len',
                'type' => 'Áo',
                'size' => 'S',
                'note' => 'Nhiều màu',
                'supplier_id' => 'MCC006',
                'supplier_name' => 'Len Mùa Đông',
                'tax' => '8838839299',
                'address' => 'Hà Đông, Hà Nội',
                'phone' => '0942382938',
                'email' => 'lenmuadong@gmail.com',
                'stock_in_id' => 'MPN006',
                'import_date' => '2025-06-13',
                'staff_id' => 'NV003',
                'stock_out_id' => 'MPX007',
                'export_date' => '2025-06-16',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 'SP0008',
                'product_name' => 'Short jean nữ rách gối',
                'quantity' => 22,
                'price' => 220000,
                'material' => 'Jean',
                'type' => 'Quần',
                'size' => 'M',
                'note' => 'Thời trang hè',
                'supplier_id' => 'MCC003',
                'supplier_name' => 'Mặc Tỉnh Dress',
                'tax' => '8709998635',
                'address' => 'Từ Sơn, Bắc Ninh',
                'phone' => '0398776395',
                'email' => 'tinhdrss44@gmail.com',
                'stock_in_id' => 'MPN001',
                'import_date' => '2025-06-08',
                'staff_id' => 'NV001',
                'stock_out_id' => 'MPX008',
                'export_date' => '2025-06-18',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 'SP0009',
                'product_name' => 'Áo khoác dạ nữ dáng dài',
                'quantity' => 6,
                'price' => 980000,
                'material' => 'Dạ',
                'type' => 'Áo khoác',
                'size' => 'XL',
                'note' => 'Dáng Hàn Quốc',
                'supplier_id' => 'MCC007',
                'supplier_name' => 'Dạ Nữ Hồng Nhung',
                'tax' => '9999887766',
                'address' => 'Ba Đình, Hà Nội',
                'phone' => '0978181919',
                'email' => 'dahongnhung@gmail.com',
                'stock_in_id' => 'MPN007',
                'import_date' => '2025-06-14',
                'staff_id' => 'NV005',
                'stock_out_id' => 'MPX009',
                'export_date' => '2025-06-19',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_id' => 'SP0010',
                'product_name' => 'Đầm maxi đi biển',
                'quantity' => 12,
                'price' => 420000,
                'material' => 'Voan lụa',
                'type' => 'Đầm',
                'size' => 'M',
                'note' => 'Chuyên du lịch',
                'supplier_id' => 'MCC008',
                'supplier_name' => 'Maxi Queen',
                'tax' => '7766554433',
                'address' => 'Cầu Giấy, Hà Nội',
                'phone' => '0906677889',
                'email' => 'maxiqueen@gmail.com',
                'stock_in_id' => 'MPN008',
                'import_date' => '2025-06-15',
                'staff_id' => 'NV001',
                'stock_out_id' => 'MPX010',
                'export_date' => '2025-06-20',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
